[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#087F8C"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#142E3E"
font = "sans serif"
